services:
  ban-bot:
    image: huydc1610/ban-bot:v2
    container_name: ban-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATA_DIR=/data
    volumes:
      - ./data/radao_data.json:/data/radao_data.json
      - ./data/nhapkho_data.json:/data/nhapkho_data.json
      - ./config.py:/app/config.py
